#!/bin/bash

set -e

immunity-qa-check \
      --migration-path './immunity_network_topology/migrations' \
      --migration-module topology


echo ''
echo 'Running checks for SAMPLE_APP'

SAMPLE_APP=1 immunity-qa-check \
              --skip-isort \
              --skip-flake8 \
              --skip-black \
              --skip-checkmigrations \
              --skip-checkendline \
              --skip-checkcommit \
              --migration-path './tests/immunity2/sample_network_topology/migrations' \
              --migration-module sample_network_topology
